version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  node:
    image: blocklistprocessingengine
    restart: "no"
    ports:
      - "10000:10000"
    depends_on:
      - "redis"
