version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  node:
    image: blocklistprocessingengine
    restart: "no"
    ports:
      - "10000:10000"
    environment:
      - KAFKA_ENDPOINT=52.174.4.93:9092
      - TOPICS=parties,transfers,accountlookups,quotes
      - RESULT_TOPIC=ruleEngineResults
      - PARTITION=0
      - AUTO_COMMIT=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - "redis"
